# veeam server config
veeam:
  # veeam api
  host: https://veeam.server:9419
  # veeam api version
  x_api_version: 1.2-rev0
  # if veeam has self-signed cert set to true
  trust_self_signed_cert: false
  # veeam admin username - can be set using env var
  username: <veeam-admin or VEEAM_ADMIN_USERNAME env var>
  # veeam admin password - can be set using env var
  password: <veeam-admin-password or VEEAM_ADMIN_PASSWORD env var>
  # excluded job types
  excluded_job_types:
    MalwareDetection: {}
    SecurityComplianceAnalyzer: {}
# influxdb config
influx:
  # influxdb api
  host: http://influxdb:8086
  # influxdb token - can be set using env var
  token: <influxdb-token or INFLUXDB_TOKEN env var>
  # influxdb organisation - can be set using env var
  org: <influxdb-org-name or INFLUXDB_ORG_NAME env var>
  # influxdb bucket - must be prepared in advance on influxdb server
  bucket: veeam(must be created)
# log level (INFO, DEBUG, ERROR)
log_level: INFO
# scrape interval
interval_seconds: 3600
