{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "govein.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  {{- if .Values.secrets.influxDBOrgName }}
  INFLUXDB_ORG_NAME: {{ b64enc .Values.secrets.influxDBOrgName}}
  {{- end }}
  INFLUXDB_TOKEN: {{ b64enc .Values.secrets.influxDBToken }}
  VEEAM_ADMIN_PASSWORD: {{ b64enc .Values.secrets.veeamAdminPassword }}
  {{- if .Values.secrets.veeamAdminUsername }}
  VEEAM_ADMIN_USERNAME: {{ b64enc .Values.secrets.veeamAdminUsername }}
  {{- end }}
type: Opaque
{{- end }}